function token() {
  return 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L3dvcmRwcmVzcyIsImlhdCI6MTY5MjEwMTk0NSwibmJmIjoxNjkyMTAxOTQ1LCJleHAiOjE2OTI3MDY3NDUsImRhdGEiOnsidXNlciI6eyJpZCI6IjEifX19.mJuiC1WALKcbRlYQKMeeopKRDugqMmQBRpAuaC-XE-o';
}

export {token}