function token() {
  return 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L3dvcmRwcmVzcyIsImlhdCI6MTY5NTcxOTE1MCwibmJmIjoxNjk1NzE5MTUwLCJleHAiOjE2OTYzMjM5NTAsImRhdGEiOnsidXNlciI6eyJpZCI6IjEifX19.lyVSwF8GsyM1yTejUlv6uE_vyIniL-DeWN5KABmz0WM';
}

export {token}